---
title: "MPM 200 R Exercise"
author: "Rachel M Hirota"
date: '2024-11-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SECTION 0
```{r}
library(beepr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(sjPlot)
library(readr)

beep(sound = 8)
```

# SECTION 1
```{r}
## Q1.  Read the Hummingbird_data.csv file in R

data <- read_csv("C:/Users/raehi/Downloads/Hummingbird_data.csv")
colnames(data)

## Q2. How many rows and columns are in the dataframe

str(data)

### rows in data = 6908
### columns in data = 12

## Q3: How many rows and columns are present in your data frame currently?

model_data = sample_n(data, 5000)
str(model_data)

### rows in model_data = 5000
### columns in model_data = 12

## Q4: How many columns are categorical variables, and how many are continuous variables in the dataset?

data_types = sapply(model_data, class)
print(data_types)

### categorical variables in model_data = 11
### continuous variables in model_data = 1

## Q5: Submit your model_data file along with your submission.

write.csv(model_data, file = "C:/Users/raehi/Downloads/Hummingbird_Rehabilitation-main/Hummingbird_Rehabilitation-main/data/Hummingbird_data_Rachel_Hirota.csv")

```

# SECTION 2
```{r}
## Q6. Please save this plot to a PDF file and submit it along with your assignment. Ensure that the size of the plot is 4 inches wide and 3 inches tall.

model_data%>% 
  group_by(Place)%>% 
  summarise(count = n_distinct(ID))

rehab = model_data  %>% 
  group_by(Place)%>% 
  summarise(count = n_distinct(ID))

p = ggplot(rehab, aes(x = Place, y = count)) +
  geom_bar(stat="identity", color = 'steelblue', fill = 'steelblue')+
  xlab('Rehabilitation center')+ ylab('Number of hummingbirds')+
  labs(title = "Number of rescued hummingbirds")

p

ggsave("model_plot_Rachel_Hirota.pdf", width = 4, height = 3, units = "in")

## Q7. Please explain the code above in words, including what each line of R code is doing, starting from the code that creates the "Rehab" object until the plot.

### organizes "model_data" dataframe by rehabilitation center (Place) and calculates counts by      distinct bird IDs by group
### line 64 - names dataframe "model_data" for organization
### line 65 - groups "model_data" by rehabilitation center (Place)
### line 66 - calculates the count of distinct bird IDs (ID) by groups

### creates new dataframe "rehab" using organization instructions from above lines 65-67
### line 68 - creates new dataframe "rehab" from named dataframe "model_data" with following                  dataframe organization instructions
### line 69 - groups "model_data" by rehabilitation center (Place)
### line 70 - calculates the count of distinct bird IDs (ID) by groups

### creates new bar chart stored in variable "p" named "Number of rescued hummingbirds" with         number of hummingbirds per rehabilitation center
### line 72 - creates variable "p" with ggplot from data from dataframe "rehab", x-axis data as     rehabilitation centers (Place) and y-axis data as distinct bird ID counts (count)
### line 73 - instructs ggplot to make bar chart with specified frequency values rather than        default counted row values, steel blue bar outline and fill color
### line 74 - instructs ggplot to add x-axis label of "Rehabilitation Center" and y-axis label      of "Number of hummingbirds"
### line 75 - instructs ggplot to add bar chart title of "Number of rescued hummingbirds"

### prints variable "p", the bar chart
### line 77 - prints variable "p"

### saves last displayed plot as PDF file using specified and default information
### line 79 - saves last displayed plot to file named "model_plot_Rachel_Hirota.pdf" with           specified size of 4 in x 3 in to working directory
```

# SECTION 3
```{r}
## Q8. What is your observation based on those tables and plots? Do you think all those are associated with the final disposition of hummingbirds? Any suggestions for statistically testing them?

### First aid as covariate
F_Aid = model_data  %>% 
  group_by(F_Aid, Disposition_binary)%>% 
  summarise(count = n_distinct(ID))
F_Aid

F_Aid_plot = ggplot(F_Aid, aes(x = Disposition_binary, y = count)) +
  geom_bar(stat="identity", color = 'darkseagreen1', fill = 'darkseagreen1')+
  xlab('Disposition outcome')+ ylab('Number of hummingbirds')+
  labs(title = "Hummingbird disposition outcomes by first aid")

F_Aid_plot + facet_grid(. ~ F_Aid)+ coord_flip()

### Died:released ratio of hummingbirds appears similar between birds that did and did not receive first aid on both the table and bar charts. Thus, it seems unlikely that first aid is associated with final disposition of the hummingbird on initial exploratory data analysis.

### Age as covariate
age = model_data  %>% 
  group_by(Age_e, Disposition_binary)%>% 
  summarise(count = n_distinct(ID))
age

age_plot = ggplot(age, aes(x = Disposition_binary, y = count)) +
  geom_bar(stat="identity", color = 'darkseagreen2', fill = 'darkseagreen2')+
  xlab('Disposition outcome')+ ylab('Number of hummingbirds')+
  labs(title = "Hummingbird disposition outcomes by age")

age_plot + facet_grid(. ~ Age_e)+ coord_flip()

### Died:released ratio of hummingbirds is extremely different between nestlings and adult-like birds on both the table and bar charts. Thus, it seems likely that age at intake is associated with final disposition of the hummingbird on initial exploratory data analysis.

### Days until brought to rehab as covariate
sex = model_data  %>% 
  group_by(Sex_e, Disposition_binary)%>% 
  summarise(count = n_distinct(ID))
sex

sex_plot = ggplot(sex, aes(x = Disposition_binary, y = count)) +
  geom_bar(stat="identity", color = 'darkseagreen3', fill = 'darkseagreen3')+
  xlab('Disposition outcome')+ ylab('Number of hummingbirds')+
  labs(title = "Hummingbird disposition outcomes by sex")

sex_plot + facet_grid(. ~ Sex_e)+ coord_flip()

### Died:released ratio of hummingbirds varies between sexes (male, female, unknown) on both the table and bar charts. Thus, it seems likely that sex is associated with final disposition of the hummingbird on initial exploratory data analysis.

### Season as covariate
season = model_data  %>% 
  group_by(season, Disposition_binary)%>% 
  summarise(count = n_distinct(ID))
season

season_plot = ggplot(season, aes(x = Disposition_binary, y = count)) +
  geom_bar(stat="identity", color = 'darkseagreen', fill = 'darkseagreen')+
  xlab('Disposition outcome')+ ylab('Number of hummingbirds')+
  labs(title = "Hummingbird disposition outcomes by season")

season_plot + facet_grid(. ~ season)+ coord_flip()

### Died:released ratio of hummingbirds is different across seasons with highest ratios in fall and winter respectively on both the table and bar charts. Thus, it seems likely that season at intake is associated with final disposition of the hummingbird on initial exploratory data analysis.

### Reason for admission as covariate
reason = model_data  %>% 
  group_by(r, Disposition_binary)%>% 
  summarise(count = n_distinct(ID))
reason

reason_plot = ggplot(reason, aes(x = Disposition_binary, y = count)) +
  geom_bar(stat="identity", color = 'darkseagreen4', fill = 'darkseagreen4')+
  xlab('Disposition outcome')+ ylab('Number of hummingbirds')+
  labs(title = "Hummingbird disposition outcomes by reason for intake")

reason_plot + facet_grid(. ~ r)+ coord_flip()

### Died:released ratio of hummingbirds varies dramatically across intake reasons on both the table and bar charts. Thus, it seems likely that reason for intake is associated with final disposition of the hummingbird on initial exploratory data analysis.

### It would be possible to perform hypothesis testing, starting with univariate analyses with appropriate statistical tests. For first aid and age (binary), a proportion test may be appropriate. For sex, season, and reason (categorical, >2 outcomes), a Chi-square test may be appropriate.

## Q10. Calculate the proportion of hummingbirds that were released versus those that died for each rehabilitation center.

proportions = model_data %>%
  group_by(Place, Disposition_binary) %>%
  summarise(count = n_distinct(ID)) %>%
  group_by(Place) %>%
  mutate(proportion = count / sum(count))

proportions

ggplot(proportions, aes(x = Place, y = proportion, fill = "deeppink")) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Rehabilitation Center") +
  ylab("Proportion") +
  labs(title = "Proportion of hummingbird outcomes as deaths by rehabilitation center")

## Q11. Merge the Species_e column into broader categories (e.g., Anna's Hummingbirds, Selasphorus genus, Non-selasphorus, Black-chinned Hummingbirds).

model_data$Species_group = ifelse(model_data$Species_e == "Selasphorus", "Selasphorus", "Non-selasphorus")

species_distribution = model_data %>%
  group_by(Species_group) %>%
  summarise(count = n_distinct(ID))

species_distribution

genus = model_data %>%
  group_by(Species_group, Disposition_binary) %>%
  summarise(count = n_distinct(ID)) %>%
  group_by(Species_group) %>%
  mutate(mortality_rate = count / sum(count))

genus

ggplot(genus, aes(x = Species_group, y = mortality_rate, fill = "pink")) +
  geom_bar(stat = "identity", position = "dodge") +
  xlab("Species Grouping") +
  ylab("Proportion") +
  labs(title = "Proportion of hummingbird outcomes as deaths by species group")

###The mortality rates are similar across Selaphorus and non-Selaphorus species of hummingbirds.

## Q12. Analyze the Trend of Hummingbird Admissions Over Time.
model_data$Admitted_date = as.Date(model_data$Admitted, format = "%m/%d/%Y")

### The argument "format" referes to the character string format to be converted. The %m refers to the characters as decimal number to be converted to month; %d refers to the characters as decimal number to be converted to the day of the month; %y refers to the characters in decimal format without century to be converted to the year.

admissions_by_month = model_data %>%
  mutate(Admitted_month = format(Admitted_date, "%Y-%m")) %>%
  group_by(Admitted_month) %>%
  summarise(count = n_distinct(ID))

admissions_by_month

p_month = ggplot(admissions_by_month, aes(x = Admitted_month, y = count)) +
  geom_bar(stat="identity", color = 'cyan3', fill = 'cyan3') +
  xlab("Month and year of admission") +
  ylab("Number of hummingbirds") +
  labs(title = "Hummingbird admissions by month and year (January 1991 to December 2016)")

p_month

admissions_by_year = model_data %>%
  mutate(Admitted_year = format(Admitted_date, "%Y")) %>%
  group_by(Admitted_year) %>%
  summarise(count = n_distinct(ID))

admissions_by_year

p_year = ggplot(admissions_by_year, aes(x = Admitted_year, y = count)) +
  geom_bar(stat="identity", color = 'cyan4', fill = 'cyan4') +
  xlab("Year of admission") +
  ylab("Number of hummingbirds") +
  labs(title = "Hummingbird admissions by year (1991-2016)")

p_year
```

